encryptionsalt: v1:QhGCoZIakRU=:v1:SC5InR/mWqgRJEcW:jRfE4mLNIthvt1ANLAVNbQhOmFwQjQ==
config:
  gcp:project: branchleft-prod
  branchleft-website-infra:region: europe-west1
  branchleft-website-infra:githubRepo: branchLeft/website
  branchleft-website-infra:gmailUser:
    secure: v1:a/QlBg0n9MqK/crZ:vPLEzUSsF8/6bTItJgxljAYDi2gqPOYsYW6jePEfQuMjYdlj/Q==
  branchleft-website-infra:gmailAppPassword:
    secure: v1:9hSxcNU3nuZIxxi6:OTA9neWs2hWUYpUDqNQg700beWwKUm2Dy7Himl5iHkA=
  branchleft-website-infra:imageTag: bootstrap-amd64-v2
